### PR TITLE
initial Dockerfile without environment config

### PR DESCRIPTION
**Pull request by KNOXDEV**
Begins to address #340. Modeled mostly after the Debian installation script.

Three things that you may want to follow this up with:
1. As mentioned in #340, a CI to build and publish this docker image. I can push this if you're interested.
2. Allow basic configuration via environment variables. Currently, you can configure the running image by mounting volumes to replace config files, but it is much more idiomatic in the Docker world to do this via env. Here is [topical example](https://github.com/namshi/docker-smtp/blob/master/entrypoint.sh).
3. The resulting docker image is quite large (~800 MB). I took steps to get it down from ~1.11GB but the need for many dynamic libraries to be present at runtime limits what I can do.

Try it out like so:
```bash
docker build . -t vsmtp:latest
docker run -it --rm -p 25:25 vsmtp:latest
nc localhost 25
```

Anyways, this is my first PR, so please take a look at let me know what you think. 👍

### CODE REVIEW

**Comment by ltabis** [comment]
@KNOXDEV Just tried it on my computer and it looks really promising. Nonetheless, wouldn't it be interesting to "mount" or link the `/etc/vsmtp/` folder to the one on the host system ? That why it's easy to configure vsmtp's rule set and config without needing to build the image every time. What do you think ?

**Review by ltabis — CHANGES_REQUESTED** [review]
Check out this [comment](https://github.com/viridIT/vSMTP/pull/522#issuecomment-1232885623).

**Comment by ltabis** [comment]
> As mentioned in https://github.com/viridIT/vSMTP/issues/340, a CI to build and publish this docker image. I can push this if you're interested.

Btw, if you have time to do that it would be awesome, thank you.

**Comment by Mathieu-Lala** [comment]
>  wouldn't it be interesting to "mount" or link the /etc/vsmtp/ folder to the one on the host system ?

Is it not usually done using a [`docker-compose.yaml`](https://docs.docker.com/compose) file ?
I am not sure if this is in the scope of our Docker image for vsmtp

**Comment by KNOXDEV** [comment]
> > wouldn't it be interesting to "mount" or link the /etc/vsmtp/ folder to the one on the host system ?
> 
> Is it not usually done using a [`docker-compose.yaml`](https://docs.docker.com/compose) file ? I am not sure if this is in the scope of our Docker image for vsmtp

I agree with this. Certain practices are frowned upon in container-land, and setting configuration via mounted volumes is one of them. 

In general, it is considered idiomatic to set configuration via environment variables. Volumes are acceptable as a means to persist data storage. For example, in the postgres docker image, it is not uncommon to mount `/var/postgres/data`. In the case of vSMTP, it would be acceptable to mount the `Maildir`, for example.

I'll push a GitHub Action that will build the docker image and push it to a repository of your configuration. To make it work, you may need to set DockerHub credentials under "Secrets" in the repository settings.

**Comment by KNOXDEV** [comment]
Action pushed, it's called `publish-docker.yaml`. You'll want to set `secrets.DOCKERHUB_USERNAME`, `secrets.DOCKERHUB_TOKEN`, possibly set the DockerHub namespace (on the last line) if you have a different one, and consider if you want to trigger it on merge with, say, `main`. It is currently set to never trigger.

**Review by ltabis — APPROVED** [review]

**Comment by ltabis** [comment]
@KNOXDEV Thanks for your PR !

**Pull request merged**
